adjective1 = input("Enter an adjective (description):")
noun1 = input("Enter a noun (person, place or thing): ")
adjective2 = input("Enter an adjective (description): ")
verb1 = input("enter a verb ending with -ing: ")
adjective3 = input("Enter an adjective (description): ")
print(f"Today i went to a {adjective1} zoo")
print(f"In an exhibit i saw a {noun1}")
print(f"The {noun1} was {adjective2} and {verb1}")
print(f"It was a very {adjective3} experience!")